version: '3.1'
services:
  # nome do serviço
  servidor_web:
      image: kaioaresi/nginx_centos7:1.0
      deploy:
          replicas: 2
          resources:
            limits:
              cpus: "0.1"
              memory: 60M
          restart_policy:
              condition: on-failure
      ports:
        - "80:80"
      networks:
        - webservice
networks:
  webservice:
