version: "3.1"
services:
  monitoramento:
    image: prom/prometheus
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.9"
          memory: 2g
      restart_policy:
          condition: on-failure
    ports:
      - "19091:9090"
    networks:
      - monitor
networks:
  monitor:
