---
- name: "install ntp"
  yum: name=ntp state=present

- name: "configurando ntp"
  template:   src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart_ntp

- name: "Iniciando ntp"
  service: name=ntpd state=started

# handlers
- name: restart ntp
  service: name=ntpd state=restarted
  listen: restart_ntp
